dataset: 'GAIC'
dataset_root: './dataset'
base_model: mobilenetv2
bbox_num: 10
scale: 'multi'
downsample: 4
augmentation: 1
image_size: 256
align_size: 9
reduced_dim: 8
num_feature_node: 256
num_features_relation: 256
num_depth: 2
num_heads: 4
mlp_dim: 1024
val_batch: 1
num_workers: 0
only_crop: True
loadweight: True
resume: None
start_iter: 0
save_folder: 'weights'
